DEEPSORT:
  MODEL_TYPE: "osnet_x_25"
  MAX_DIST: 0.1 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 1.0 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 20 # Maximum number of missed misses before a track is deleted
  N_INIT: 0 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 40 # Maximum size of the appearance descriptors gallery
  LAMBDA: 0.5 
