#!/bin/bash

DIR="./configs/$1"
OUTPUT="./results/$1"
FILES=`ls $DIR`

count=0
for f in $FILES
do
	config="$DIR/$f"
	output="$OUTPUT/$f"
	execute="python ../track.py --yolo_weights ./runs/best.pt \
--source ./data/max_0008_trimmed \
--conf-thres 0.6 \
--save-txt \
--save-vid \
--config_deepsort $config \
--output $output &"
	echo "executing $execute"
	eval $execute
	(( count++ ))
	if [ "$count" -eq "9" ]; then
		echo "waiting for batch of 10 to finish"
		eval "wait"
	fi
done
eval "wait"
echo "done"
